---
title: "Supplemental Information"
format:
  plos-pdf:
    number-sections: false
    journal:
      # This is an identifier for the target journal: 
      # from https://plos.org/resources/writing-center/ following submission guidelines link, the identifier is the part of the URL after https://journals.plos.org/<id>/s/submission-guidelines
      id: plosone
    include-in-header:
      text: |
        % Remove comment for double spacing
        % \usepackage{setspace} 
        % \doublespacing
---

```{r, include=FALSE, warning=FALSE}
library(readxl)
library(knitr)
library(tidyverse)
library(here)
```

```{r, include=FALSE}
mean_values <- read_excel(here("data/all_rf_mean_results.xlxs"))
```

```{r}
#| echo: false
#| label: tbl-modelsummary
#| tbl-cap: 

mean_values %>%
  arrange(MAE) %>%
  # rename()
  # knitr::kable(., digits = 3, col.names = c("Model name", "OOB MSE", "RMSE", "MAE", "$r^2$", "Marker", "Taxonomic Level", "Enironmental parameters"), escape = FALSE) %>%
  kableExtra::kbl(., digits = 3, col.names = c("Model name", "OOB MSE", "RMSE", "MAE", "$r^2$", "Marker", "Taxonomic Level", "Enironmental parameters"), booktabs = TRUE)
  # kableExtra::kable_classic() %>%
```