---
format: 
  pdf:
    keep-tex: true
crossref: 
  tbl-title: 'Table S'
geometry: 
  - left=0.75in
  - right=0.75in
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
---

```{r, include=FALSE, warning=FALSE}
library(readxl)
library(knitr)
library(tidyverse)
library(here)

options(kableExtra.latex.load_packages = FALSE) 
library(kableExtra)
```

```{r, include=FALSE}
mean_values <- read_excel(here("data/all_rf_mean_results.xlxs"))
```

```{r}
#| echo: false

mean_values %>%
  arrange(MAE) %>%
  kbl(.,
      caption = "Summary statics for all random forest models. Values are means for 100 runs of each model. OOB MSE = out-of-bag mean squared error, RMSE = root mean squared error, MAE = mean absolute error, OTU = Operational taxonomic unit.",
      digits = 3,
      booktabs = TRUE,
      col.names = c("Model name", "OOB MSE", "RMSE", "MAE", "r^{2}^", "Marker", "Taxonomic Level", "Environmental parameters")) %>%
  column_spec(7, width = "2cm") %>%
  column_spec(8, width = "2cm")
  
  
  # kable(
  #   format = "latex",
  #   caption = "Summary statics for all random forest models. Values are means for 100 runs of each model. OOB MSE = out-of-bag mean squared error, RMSE = root mean squared error, MAE = mean absolute error, OTU = Operational taxonomic unit.",
  #   col.names = c("Model name", "OOB MSE", "RMSE", "MAE", "$r^2$", "Marker", "Taxonomic Level", "Enironmental parameters"),
  #   digits = 3,
  #   booktabs = TRUE
  # ) 
  # knitr::kable(
  #   format = "latex",
  #   col.names = c("Model name", "OOB MSE", "RMSE", "MAE", "$r^2$", "Marker", "Taxonomic Level", "Enironmental parameters"),
  #   digits = 3,
  #   booktabs = TRUE,
  #   longtable = TRUE,
  #   align = "l",
  #   escape = FALSE)
```